media:
  input: assets
  output: assets

content:
  - label: Pages
    type: collection
    path: /
    files:
      - name: index
        label: Home Page (index.html)
        file: index.html
        fields:
          - name: body
            label: Page Content
            type: code
            options:
              language: html

      - name: gallery
        label: Gallery Page (gallery.html)
        file: gallery.html
        fields:
          - name: body
            label: Page Content
            type: code
            options:
              language: html

      - name: style
        label: Stylesheet (style.css)
        file: style.css
        fields:
          - name: body
            label: CSS Code
            type: code
            options:
              language: css